name: CI

env:
  REPO: "${{ vars.REPO }}"
  VERSION: "${{ github.ref_name }}"
  BUILD_PLATFORMS: "linux/amd64,linux/arm64"
  PARALLELIZE: "false"
  GO_VERSION: "1.19.12"

defaults:
  run:
    shell: bash

on:
  push:

jobs:
    greeting_job:
        runs-on: ubuntu-latest
        steps:
            - name: "echo env"
              run: |
                echo $REPO
                # Exec scripts
                for i in `ls ${GITHUB_WORKSPACE}/scripts/*.sh`;do bash "$i";done