name: CI

env:
  REPO: "${{ vars.REPO || 'sealio' }}"
  VERSION: "${{ github.ref_name }}"
  BUILD_PLATFORMS: "linux/amd64,linux/arm64"
  PARALLELIZE: "false"
  GO_VERSION: "1.19.12"

on:
  push:

jobs:
    greeting_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                # checkout the whole histories for commitsar,
                # currently commitsar needs full git objects to work correctly.
                fetch-depth: 0
                persist-credentials: false
            - name: "echo env"
              run: |
                echo ${{ env.REPO }}
                # Exec scripts
                for i in `ls ${GITHUB_WORKSPACE}/scripts/*.sh`;do bash "$i";done